Dev
jacob-js/Thegym-buildit-nextjs-practice pull request #1
Opened 2022-10-25 17:11 UTC by jacob-js

## Pages done : 

✔️ Home page
✔️ About page

2022-10-25 17:14 UTC, jacob-js commented
![](https://github.trello.services/images/mini-trello-icon.png) [Jacob M. Buildit (Nextjs Practice)](https://trello.com/c/RcPfHi5s/142-jacob-m-buildit-nextjs-practice)

2022-10-26 18:30 UTC, alain-kubwayo requested changes
Looks good!

2022-10-27 09:41 UTC, alain-kubwayo approved these changes

2022-10-28 15:01 UTC, Morrism1 approved these changes
Looks Good! 🚀

2023-03-12 18:10 UTC, merged